# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib rete, .registration = TRUE
NULL

# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_rete_wrappers", use_symbols = TRUE, package_name = "rete")

#' @usage NULL
#' @useDynLib rete, .registration = TRUE
NULL

#' Build a complete `.rete` file image from RDF text. `card_json` may be ""
#' (no card); `pyramid_algo` is "louvain", "types", or "none". Internal —
#' users call the documented `rete_build()`.
#' @noRd
build_dataset <- function(text, format, card_json, pyramid_algo, text_index) .Call(wrap__build_dataset, text, format, card_json, pyramid_algo, text_index)

#' Version of the Rust engine compiled into this package. The package's own
#' version tracks the binding and shares only the engine's major.minor, so this
#' is what answers "which engine am I actually running?".
#' @export
engine_version <- function() .Call(wrap__engine_version)

RGraph <- new.env(parent = emptyenv())

RGraph$from_path <- function(path) .Call(wrap__RGraph__from_path, path)

RGraph$from_url <- function(url) .Call(wrap__RGraph__from_url, url)

RGraph$from_bytes <- function(data) .Call(wrap__RGraph__from_bytes, data)

RGraph$query <- function(query, reason) .Call(wrap__RGraph__query, self, query, reason)

RGraph$info <- function() .Call(wrap__RGraph__info, self)

RGraph$graph_names <- function() .Call(wrap__RGraph__graph_names, self)

RGraph$prefix_search <- function(prefix, limit) .Call(wrap__RGraph__prefix_search, self, prefix, limit)

RGraph$text_search <- function(words, contains, limit) .Call(wrap__RGraph__text_search, self, words, contains, limit)

RGraph$schema <- function() .Call(wrap__RGraph__schema, self)

RGraph$card <- function() .Call(wrap__RGraph__card, self)

RGraph$stats <- function() .Call(wrap__RGraph__stats, self)

RGraph$content_hash <- function() .Call(wrap__RGraph__content_hash, self)

#' @export
`$.RGraph` <- function (self, name) { func <- RGraph[[name]]; environment(func) <- environment(); func }

#' @export
`[[.RGraph` <- `$.RGraph`

# nolint end
