#!/usr/bin/env python3
"""GBIF Spain+Switzerland bird occurrences -> N-Triples for a rete geo+taxonomy graph.

Reads the local extract data/gbif_birds/birds.parquet (see gbif_birds_extract.py)
and emits two files:

  birds_tbox.nt  - the taxonomy T-Box + country/dataset nodes (small, Python).
                   Each taxon rank is an rdfs:Class with a subClassOf chain
                   Species <= Genus <= Family <= Order <= Aves <= Chordata <=
                   Animalia. THIS is what gives the schema pyramid its levels:
                   ask at the Order level and never descend to species.
  birds_occ.nt   - one node per occurrence (~tens of millions), generated by
                   DuckDB SQL for speed: rdf:type <species class>, a GeoSPARQL
                   POINT, country, year, basis-of-record and source dataset.

Model IRIs round-trip to live GBIF: occurrence = gbif.org/occurrence/<gbifid>,
species class carries owl:sameAs gbif.org/species/<specieskey>.
Source: GBIF AWS Open Data snapshot, CC-BY-NC.
"""
import os, re, sys, urllib.parse, duckdb

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(HERE, "data", "gbif_birds")
# Read the batched extract's parts by default; override with GBIF_PARQUET (e.g. a
# single part for a timed test build).
PARQUET = os.environ.get("GBIF_PARQUET", os.path.join(DATA, "parts", "part_*.parquet"))
OUT_TBOX = os.environ.get("GBIF_OUT_TBOX", os.path.join(DATA, "birds_tbox.nt"))
OUT_OCC = os.environ.get("GBIF_OUT_OCC", os.path.join(DATA, "birds_occ.nt"))

NS = "https://w3id.org/rete/gbif/"                # dataset namespace (neutral w3id PURL, not a project host)
TAXON = NS + "taxon/"                              # taxon classes
OCC = "https://www.gbif.org/occurrence/"          # round-trips to GBIF
GBIF_SP = "https://www.gbif.org/species/"          # round-trips to GBIF
RDF = "http://www.w3.org/1999/02/22-rdf-syntax-ns#type"
RDFS = "http://www.w3.org/2000/01/rdf-schema#"
OWL = "http://www.w3.org/2002/07/owl#"
DWC = "http://rs.tdwg.org/dwc/terms/"
DCT = "http://purl.org/dc/terms/"
GEO = "http://www.opengis.net/ont/geosparql#"
XSD = "http://www.w3.org/2001/XMLSchema#"
SUBCLASS = RDFS + "subClassOf"
LABEL = RDFS + "label"

# Standard vocab (was a bespoke `vocab#` namespace):
VOID = "http://rdfs.org/ns/void#"
SCHEMA = "http://schema.org/"
V = NS + "vocab#"                # kept only for the Country/Dataset class IRIs
IN_COUNTRY = DCT + "spatial"     # occurrence's spatial coverage = its country (Dublin Core)
SOURCE_DS = VOID + "inDataset"   # occurrence is in this VoID dataset
RANK = DWC + "taxonRank"         # Darwin Core taxonomic rank (literal)

RANKS = ["kingdom", "phylum", "class", "order_", "family", "genus"]  # species handled by key
RANK_LABEL = {"kingdom": "kingdom", "phylum": "phylum", "class": "class",
              "order_": "order", "family": "family", "genus": "genus", "species": "species"}


def esc(s):
    return str(s).replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ").replace("\r", " ").replace("\t", " ")


def slug(name):
    return urllib.parse.quote(str(name).replace(" ", "_"), safe="")


def taxon_iri(rank, name):
    return f"{TAXON}{RANK_LABEL[rank]}/{slug(name)}"


def species_iri(specieskey):
    return f"{TAXON}species/{specieskey}"


def emit_tbox(con):
    fh = open(OUT_TBOX, "w", encoding="utf-8", newline="\n")
    n = 0

    def t(s, p, o_iri=None, lit=None, dt=None):
        nonlocal n
        if o_iri is not None:
            o = f"<{o_iri}>"
        elif dt is not None:
            o = f'"{esc(lit)}"^^<{dt}>'
        else:
            o = f'"{esc(lit)}"'
        fh.write(f"<{s}> <{p}> {o} .\n")
        n += 1

    # --- the class metadata (vocab) ---
    for cls, comment in [("Occurrence", "A single georeferenced bird observation or specimen record")]:
        t(V + cls, RDF, RDFS + "Class"); t(V + cls, LABEL, lit=cls)
        t(V + cls, RDFS + "comment", lit=comment)

    # --- distinct taxa: build the subClassOf chain once ---
    rows = con.execute("""
        SELECT DISTINCT kingdom, phylum, class, order_, family, genus, species, specieskey
        FROM read_parquet(?)
    """, [PARQUET]).fetchall()
    seen_class = set()

    def ensure_class(iri, label, rank):
        if iri in seen_class:
            return
        seen_class.add(iri)
        t(iri, RDF, RDFS + "Class")
        t(iri, LABEL, lit=label)
        t(iri, RANK, lit=rank)

    n_species = 0
    for kingdom, phylum, cls, order_, family, genus, species, specieskey in rows:
        chain = []  # (iri, label, rank) from broad -> narrow, non-null only
        for rank in RANKS:
            name = {"kingdom": kingdom, "phylum": phylum, "class": cls,
                    "order_": order_, "family": family, "genus": genus}[rank]
            if name:
                chain.append((taxon_iri(rank, name), name, RANK_LABEL[rank]))
        # species leaf (keyed)
        sp_iri = species_iri(specieskey)
        chain.append((sp_iri, species or str(specieskey), "species"))
        # register classes + subClassOf links up the chain
        for i, (iri, label, rank) in enumerate(chain):
            ensure_class(iri, label, rank)
            if i > 0:
                t(chain[i][0], SUBCLASS, chain[i - 1][0])  # narrower subClassOf broader
        # species links out to live GBIF + carries its key
        t(sp_iri, OWL + "sameAs", f"{GBIF_SP}{specieskey}")
        n_species += 1

    # --- country nodes ---
    for cc, name in [("ES", "Spain"), ("CH", "Switzerland")]:
        c = f"{NS}country/{cc}"
        t(c, RDF, SCHEMA + "Country"); t(c, LABEL, lit=name); t(c, DCT + "identifier", lit=cc)
    t(SCHEMA + "Country", RDF, RDFS + "Class"); t(SCHEMA + "Country", LABEL, lit="Country")

    # --- dataset nodes (provenance): label = the GBIF datasetKey for now ---
    ds = con.execute("SELECT DISTINCT datasetkey FROM read_parquet(?) WHERE datasetkey IS NOT NULL", [PARQUET]).fetchall()
    for (dk,) in ds:
        d = f"https://www.gbif.org/dataset/{dk}"
        t(d, RDF, VOID + "Dataset"); t(d, LABEL, lit=dk)
    t(VOID + "Dataset", RDF, RDFS + "Class"); t(VOID + "Dataset", LABEL, lit="Source dataset")

    fh.close()
    print(f"tbox: {n:,} triples, {n_species:,} species, {len(ds):,} datasets", file=sys.stderr)


def emit_occurrences(con):
    """Bulk per-occurrence triples via DuckDB SQL (fast). Each SELECT emits one
    predicate as a full N-Triples line; UNION ALL then COPY to a raw text file."""
    sp = f"'{TAXON}species/'"
    occ = f"'<{OCC}' || gbifid || '>'"
    q = f"""
    COPY (
      -- rdf:type <species class>  (drives the type/schema pyramid)
      SELECT {occ} || ' <{RDF}> <{TAXON}species/' || specieskey || '> .' AS line
        FROM read_parquet('{PARQUET}')
      UNION ALL
      -- GeoSPARQL point
      SELECT {occ} || ' <{GEO}asWKT> "POINT(' || lon || ' ' || lat || ')"^^<{GEO}wktLiteral> .'
        FROM read_parquet('{PARQUET}')
      UNION ALL
      -- country
      SELECT {occ} || ' <{IN_COUNTRY}> <{NS}country/' || countrycode || '> .'
        FROM read_parquet('{PARQUET}')
      UNION ALL
      -- year (gYear) where present
      SELECT {occ} || ' <{DWC}year> "' || year || '"^^<{XSD}gYear> .'
        FROM read_parquet('{PARQUET}') WHERE year IS NOT NULL
      UNION ALL
      -- basis of record
      SELECT {occ} || ' <{DWC}basisOfRecord> "' || basisofrecord || '" .'
        FROM read_parquet('{PARQUET}') WHERE basisofrecord IS NOT NULL
      UNION ALL
      -- source dataset
      SELECT {occ} || ' <{SOURCE_DS}> <https://www.gbif.org/dataset/' || datasetkey || '> .'
        FROM read_parquet('{PARQUET}') WHERE datasetkey IS NOT NULL
      UNION ALL
      -- individual count: the estimated number of individuals in the sighting
      -- (dwc:individualCount, ~41% populated). This is the per-occurrence
      -- "number estimated"; the species-level aggregate lives in birds_enrich.nt.
      SELECT {occ} || ' <{DWC}individualCount> "' || individualcount || '"^^<{XSD}integer> .'
        FROM read_parquet('{PARQUET}') WHERE individualcount IS NOT NULL AND individualcount > 0
    ) TO '{OUT_OCC}' (FORMAT csv, HEADER false, QUOTE '', DELIMITER E'\\x01');
    """
    con.execute(q)
    # line count
    n = con.execute("SELECT COUNT(*) FROM read_csv(?, columns={'l':'VARCHAR'}, quote='', delim=E'\\x01', header=false)", [OUT_OCC]).fetchone()[0]
    print(f"occurrences: {n:,} triples -> {OUT_OCC}", file=sys.stderr)


def main():
    con = duckdb.connect()
    con.execute("SET preserve_insertion_order=false;")
    emit_tbox(con)
    emit_occurrences(con)


if __name__ == "__main__":
    main()
