#!/usr/bin/env python3
"""Emit the catalog `rag: { ... }` block from the embedded index files — one entry
per dataset that has a semantic index, with token-free graphplaza URLs + the doc
count. Print to stdout; the block replaces the existing `rag:` in catalog.js."""
import glob, json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RAG = os.path.join(ROOT, "data", "rag")

entries = []
for idx in sorted(glob.glob(os.path.join(RAG, "*_emb_index.json"))):
    key = os.path.basename(idx)[:-len("_emb_index.json")]
    if not os.path.exists(os.path.join(RAG, key + "_emb.f32")):
        continue
    n = len(json.load(open(idx, encoding="utf-8")))
    base = "https://data.graphplaza.com/%s-rag/%s_emb" % (key, key)
    entries.append(
        '    "%s": { emb: "%s.f32", index: "%s_index.json", '
        'model: "Xenova/multilingual-e5-small", queryPrefix: "query: ", dim: 384, count: %d },'
        % (key, base, base, n))

print("  // Semantic-search (RAG) indexes — precomputed doc embeddings on R2/graphplaza")
print("  // (token-free) + the model that embeds the query. Generated by scripts/rag_*.")
print("  rag: {")
print("\n".join(entries))
print("  },")
print("\n// %d datasets have a semantic index" % len(entries), flush=True)
